// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:directus_api_manager/src/annotations.dart' as prefix0;
import 'package:directus_api_manager/src/model/directus_user.dart' as prefix6;
import 'package:vr_web_admin/models/player.dart' as prefix3;
import 'package:vr_web_admin/models/sessions.dart' as prefix4;
import 'package:vr_web_admin/models/user_detail.dart' as prefix5;
import 'package:vr_web_admin/page/listexplointant_viewmodel.dart' as prefix2;
import 'package:vr_web_admin/page/login_viewmodel.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.DirectusCollection(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'LoginViewModel',
            r'.LoginViewModel',
            134217735,
            0,
            const prefix0.DirectusCollection(),
            const <int>[0],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (_useCases, _router) =>
                  b ? prefix1.LoginViewModel(_useCases, _router) : null
            },
            0,
            -1,
            const <int>[-1],
            const <Object>[const prefix0.DirectusCollection()],
            null),
        r.NonGenericClassMirrorImpl(
            r'ListExploitantViewModel',
            r'.ListExploitantViewModel',
            134217735,
            1,
            const prefix0.DirectusCollection(),
            const <int>[1],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (_useCases) =>
                  b ? prefix2.ListExploitantViewModel(_useCases) : null
            },
            1,
            -1,
            const <int>[-1],
            const <Object>[const prefix0.DirectusCollection()],
            null),
        r.NonGenericClassMirrorImpl(
            r'Players',
            r'.Players',
            134217735,
            2,
            const prefix0.DirectusCollection(),
            const <int>[2],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (rawReceivedData) =>
                  b ? prefix3.Players(rawReceivedData) : null
            },
            2,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix0.DirectusCollection(),
              const prefix0.CollectionMetadata(endpointName: "players")
            ],
            null),
        r.NonGenericClassMirrorImpl(
            r'Sessions',
            r'.Sessions',
            134217735,
            3,
            const prefix0.DirectusCollection(),
            const <int>[3, 4],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {
              r'newItem': (bool b) =>
                  () => b ? prefix4.Sessions.newItem() : null,
              r'': (bool b) => (rawReceivedData) =>
                  b ? prefix4.Sessions(rawReceivedData) : null
            },
            3,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix0.DirectusCollection(),
              const prefix0.CollectionMetadata(endpointName: "session")
            ],
            null),
        r.NonGenericClassMirrorImpl(
            r'UsersDetails',
            r'.UsersDetails',
            134217735,
            4,
            const prefix0.DirectusCollection(),
            const <int>[5],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (rawReceivedData) =>
                  b ? prefix5.UsersDetails(rawReceivedData) : null
            },
            4,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix0.DirectusCollection(),
              const prefix0.CollectionMetadata(endpointName: "users_details")
            ],
            null),
        r.NonGenericClassMirrorImpl(
            r'DirectusUser',
            r'.DirectusUser',
            134217735,
            5,
            const prefix0.DirectusCollection(),
            const <int>[6, 7],
            const <int>[],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (rawReceivedData) =>
                  b ? prefix6.DirectusUser(rawReceivedData) : null,
              r'newDirectusUser': (bool b) =>
                  () => b ? prefix6.DirectusUser.newDirectusUser() : null
            },
            5,
            -1,
            const <int>[-1],
            const <Object>[const prefix0.DirectusCollection()],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[0, 1],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'', 0, 1, -1, -1, -1, null, const <int>[2],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'', 0, 2, -1, -1, -1, null, const <int>[3],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'newItem', 0, 3, -1, -1, -1, null, const <int>[],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'', 0, 3, -1, -1, -1, null, const <int>[4],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'', 0, 4, -1, -1, -1, null, const <int>[5],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'', 0, 5, -1, -1, -1, null, const <int>[6],
            const prefix0.DirectusCollection(), const []),
        r.MethodMirrorImpl(r'newDirectusUser', 0, 5, -1, -1, -1, null,
            const <int>[], const prefix0.DirectusCollection(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'_useCases',
            134349862,
            0,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_router',
            134349862,
            0,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_useCases',
            134349862,
            1,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'rawReceivedData',
            151127046,
            2,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'rawReceivedData',
            151126022,
            4,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'rawReceivedData',
            151127046,
            5,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'rawReceivedData',
            151126022,
            6,
            const prefix0.DirectusCollection(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.LoginViewModel,
        prefix2.ListExploitantViewModel,
        prefix3.Players,
        prefix4.Sessions,
        prefix5.UsersDetails,
        prefix6.DirectusUser
      ],
      6,
      {},
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:vr_web_admin/page/login_viewmodel.dart'),
            const prefix0.DirectusCollection(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(
                'package:vr_web_admin/page/listexplointant_viewmodel.dart'),
            const prefix0.DirectusCollection(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:vr_web_admin/models/player.dart'),
            const prefix0.DirectusCollection(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:vr_web_admin/models/sessions.dart'),
            const prefix0.DirectusCollection(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:vr_web_admin/models/user_detail.dart'),
            const prefix0.DirectusCollection(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(
                'package:directus_api_manager/src/model/directus_user.dart'),
            const prefix0.DirectusCollection(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
